### ISSUE TITLE
Explore Premake build system

### ISSUE THREAD

**Issue by manning390** [manning390/computer-game#13]
I'm not a huge fan of cmake. It is difficult to read, requires multiple files, and depends on several invisible environment variables to port to other platforms.

Cherno showed Premake and it is compatible with MS Studio and command line use. Looks easy to read and configure.

https://youtu.be/sULV3aB2qeU

We should explore if this is easier for us to maintain the project with.

I think by using git submodules on our libraries in combination with this will remove all setup time by developers.

**Comment by goosinator868** [comment]
Sounds good. Ill look at it when I have time.Sent via the Samsung Galaxy S10, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Michael Manning <notifications@github.com> Date: 1/14/21  12:28 PM  (GMT-08:00) To: manning390/computer-game <computer-game@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [manning390/computer-game] Explore Premake build system (#13) 
I'm not a huge fan of cmake. It is difficult to read, requires multiple files, and depends on several invisible environment variables to port to other platforms.
Cherno showed Premake and it is compatible with MS Studio and command line use. Looks easy to read and configure.
https://youtu.be/sULV3aB2qeU
We should explore if this is easier for us to maintain the project with.
I think by using git submodules on our libraries in combination with this will remove all setup time by developers.

**Comment by manning390** [comment]
I pushed a branch with some premake and vendor stuff done. I haven't run the build yet since I am not sure how to rope in SFML.

**Comment by manning390** [comment]
At the moment I think we have a viable solution with CMake. Going to focus on game dev and less on building things and close this.
